#!/usr/bin/env python3
"""
Flutter Dependency Version Checker
Checks pub.dev for latest stable versions of Flutter packages
Usage: python check_latest_versions.py [package_name]
"""

import sys
import json
import urllib.request
import urllib.error
from typing import Dict, Optional, List, Tuple

# ANSI Colors
class Colors:
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    BLUE = '\033[0;34m'
    BOLD = '\033[1m'
    NC = '\033[0m'  # No Color

# Recommended packages with minimum acceptable scores
DEFAULT_PACKAGES = {
    'dependencies': [
        'hooks_riverpod',
        'flutter_hooks',
        'go_router',
        'either_dart',
        'equatable',
        'intl',
        'supabase_flutter',
        'dio',
        'json_annotation',
        'flutter_svg',
        'google_fonts',
        'flutter_animate',
        'flutter_screenutil',
        'shared_preferences',
        'loggy',
        'flutter_loggy',
        'permission_handler',
        'file_picker',
        'image_picker',
        'url_launcher',
        'share_plus',
        'path',
        'q_architecture',
    ],
    'dev_dependencies': [
        'build_runner',
        'json_serializable',
        'flutter_lints',
        'custom_lint',
        'riverpod_lint',
        'mocktail',
    ]
}

def fetch_json(url: str) -> Optional[Dict]:
    """Fetch JSON data from URL"""
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            data = response.read()
            return json.loads(data.decode('utf-8'))
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError) as e:
        print(f"{Colors.RED}Error fetching {url}: {e}{Colors.NC}", file=sys.stderr)
        return None

def get_latest_version(package: str) -> Optional[str]:
    """Get latest stable version from pub.dev"""
    url = f"https://pub.dev/api/packages/{package}"
    data = fetch_json(url)
    
    if data and 'latest' in data and 'version' in data['latest']:
        return data['latest']['version']
    
    return None

def get_package_score(package: str) -> Optional[Tuple[int, int]]:
    """Get package pub points score"""
    url = f"https://pub.dev/api/packages/{package}/score"
    data = fetch_json(url)
    
    if data and 'grantedPoints' in data and 'maxPoints' in data:
        return (data['grantedPoints'], data['maxPoints'])
    
    return None

def get_package_metrics(package: str) -> Optional[Dict]:
    """Get package metrics (popularity, likes, etc.)"""
    url = f"https://pub.dev/api/packages/{package}/metrics"
    data = fetch_json(url)
    
    if data and 'score' in data:
        return {
            'popularity': data['score'].get('popularityScore', 0),
            'likes': data['score'].get('likeCount', 0),
        }
    
    return None

def check_package(package: str, verbose: bool = True) -> Optional[Dict]:
    """
    Check package and return version info
    
    Returns:
        Dict with version, score, and metrics
    """
    if verbose:
        print(f"{Colors.YELLOW}Checking {package}...{Colors.NC}")
    
    version = get_latest_version(package)
    
    if not version:
        if verbose:
            print(f"{Colors.RED}✗{Colors.NC} Failed to check {package}\n")
        return None
    
    score = get_package_score(package)
    metrics = get_package_metrics(package)
    
    result = {
        'package': package,
        'version': version,
        'score': score,
        'metrics': metrics,
    }
    
    if verbose:
        score_str = f"{score[0]}/{score[1]}" if score else "N/A"
        popularity = f"{metrics['popularity']:.0%}" if metrics else "N/A"
        
        print(f"{Colors.GREEN}✓{Colors.NC} {package}: ^{version}")
        print(f"  Score: {score_str} | Popularity: {popularity}")
        
        # Warning if score is low
        if score and score[0] < 130:
            print(f"  {Colors.YELLOW}⚠ Warning: Low pub score (< 130){Colors.NC}")
        
        print()
    
    return result

def generate_pubspec_yaml(results: Dict[str, List[Dict]]) -> str:
    """Generate pubspec.yaml snippet with latest versions"""
    output = []
    
    output.append("# Generated by check_latest_versions.py")
    output.append("# Copy these to your pubspec.yaml\n")
    
    output.append("dependencies:")
    output.append("  flutter:")
    output.append("    sdk: flutter")
    output.append("")
    
    for pkg_info in results.get('dependencies', []):
        if pkg_info:
            output.append(f"  {pkg_info['package']}: ^{pkg_info['version']}")
    
    output.append("")
    output.append("dev_dependencies:")
    output.append("  flutter_test:")
    output.append("    sdk: flutter")
    output.append("")
    
    for pkg_info in results.get('dev_dependencies', []):
        if pkg_info:
            output.append(f"  {pkg_info['package']}: ^{pkg_info['version']}")
    
    return "\n".join(output)

def generate_markdown_report(results: Dict[str, List[Dict]]) -> str:
    """Generate markdown report of package versions"""
    output = []
    
    output.append("# Flutter Dependency Version Report\n")
    output.append(f"Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    for dep_type in ['dependencies', 'dev_dependencies']:
        output.append(f"## {dep_type.replace('_', ' ').title()}\n")
        output.append("| Package | Version | Score | Status |")
        output.append("|---------|---------|-------|--------|")
        
        for pkg_info in results.get(dep_type, []):
            if pkg_info:
                package = pkg_info['package']
                version = pkg_info['version']
                score = pkg_info.get('score')
                
                score_str = f"{score[0]}/{score[1]}" if score else "N/A"
                
                # Status indicator
                if score and score[0] >= 130:
                    status = "✅ Excellent"
                elif score and score[0] >= 100:
                    status = "⚠️ Good"
                else:
                    status = "❌ Low Score"
                
                output.append(f"| {package} | ^{version} | {score_str} | {status} |")
        
        output.append("")
    
    return "\n".join(output)

def main():
    """Main function"""
    print(f"{Colors.BLUE}{Colors.BOLD}🔍 Flutter Dependency Version Checker{Colors.NC}\n")
    
    if len(sys.argv) > 1:
        # Check specific package
        package = sys.argv[1]
        result = check_package(package, verbose=True)
        
        if result:
            print(f"\n{Colors.GREEN}✅ Version check complete!{Colors.NC}")
            print(f"\nAdd to pubspec.yaml:")
            print(f"  {package}: ^{result['version']}")
        else:
            sys.exit(1)
    else:
        # Check all default packages
        print(f"{Colors.BLUE}Checking all recommended packages...{Colors.NC}\n")
        
        results = {
            'dependencies': [],
            'dev_dependencies': []
        }
        
        for dep_type in ['dependencies', 'dev_dependencies']:
            for package in DEFAULT_PACKAGES[dep_type]:
                result = check_package(package, verbose=True)
                results[dep_type].append(result)
        
        # Generate outputs
        print(f"\n{Colors.GREEN}{Colors.BOLD}✅ Version check complete!{Colors.NC}\n")
        
        # YAML output
        yaml_output = generate_pubspec_yaml(results)
        print(f"{Colors.BLUE}━━━ PUBSPEC.YAML ━━━{Colors.NC}")
        print(yaml_output)
        print()
        
        # Save to file
        try:
            with open('.cursor/tools/latest_versions.yaml', 'w') as f:
                f.write(yaml_output)
            print(f"{Colors.GREEN}✓ Saved to .cursor/tools/latest_versions.yaml{Colors.NC}")
        except Exception as e:
            print(f"{Colors.YELLOW}⚠ Could not save YAML: {e}{Colors.NC}")
        
        # Markdown report
        md_output = generate_markdown_report(results)
        try:
            with open('.cursor/tools/dependency_report.md', 'w') as f:
                f.write(md_output)
            print(f"{Colors.GREEN}✓ Saved report to .cursor/tools/dependency_report.md{Colors.NC}")
        except Exception as e:
            print(f"{Colors.YELLOW}⚠ Could not save report: {e}{Colors.NC}")
        
        print(f"\n{Colors.YELLOW}💡 Tip: Copy versions from latest_versions.yaml to your pubspec.yaml{Colors.NC}")

if __name__ == '__main__':
    main()

